/* polars.js — GENERATED by tools/polar.js from the live physics (centaur).
   Best steady STW (kn) and the sheet that achieved it, by TWS x TWA.
   Regenerate after any change to the sail model:  node tools/polar.js */
(function (S) {
  'use strict';
  S.POLARS = {
    spec: "centaur",
    tws: [8,12,16,20],
    twa: [35,45,55,65,75,85,95,105,115,125,135,145,155,165,175],
    stw: [[1.4,2.2,2.67,3.13,3.48,3.69,3.72,3.75,3.67,3.47,3.29,3.25,3.21,3.18,3.17],[2.41,3.61,4.36,4.74,4.89,5.07,5.07,5.05,4.99,4.86,4.72,4.66,4.63,4.61,4.59],[3.3,4.54,5.08,5.33,5.58,5.66,5.72,5.74,5.7,5.6,5.46,5.47,5.47,5.46,5.45],[4,5.03,5.47,5.79,5.95,6.12,6.19,6.21,6.19,6.13,6.01,6.04,6.05,6.05,6.06]],
    sheet: [[5,10,15,25,30,35,45,50,60,70,85,60,70,75,85],[5,10,15,20,30,35,45,50,60,75,85,60,70,75,85],[5,10,15,25,30,40,45,55,65,75,60,65,70,75,85],[5,10,15,25,30,40,50,60,70,80,60,65,70,80,85]],
    beat: [45,45,45,45],   // TWA of best upwind VMG per TWS
    run: [175,175,175,175]     // TWA of best downwind VMG per TWS
  };
  /** target boat speed (kn) at this true wind, linearly interpolated */
  S.POLARS.target = function (twsKn, twaDeg) {
    var P = S.POLARS, U = S.U;
    var a = Math.abs(twaDeg);
    if (a < P.twa[0]) a = P.twa[0];
    if (a > P.twa[P.twa.length - 1]) a = P.twa[P.twa.length - 1];
    var ti = 0; while (ti < P.tws.length - 2 && P.tws[ti + 1] < twsKn) ti++;
    var ai = 0; while (ai < P.twa.length - 2 && P.twa[ai + 1] < a) ai++;
    var tf = U.clamp((twsKn - P.tws[ti]) / (P.tws[ti + 1] - P.tws[ti]), 0, 1);
    var af = U.clamp((a - P.twa[ai]) / (P.twa[ai + 1] - P.twa[ai]), 0, 1);
    var lo = U.lerp(P.stw[ti][ai], P.stw[ti][ai + 1], af);
    var hi = U.lerp(P.stw[ti + 1][ai], P.stw[ti + 1][ai + 1], af);
    return U.lerp(lo, hi, tf);
  };
  /** best beat angle (deg TWA) at this wind speed */
  S.POLARS.beatAt = function (twsKn) {
    var P = S.POLARS;
    var ti = 0; while (ti < P.tws.length - 2 && P.tws[ti + 1] < twsKn) ti++;
    var tf = S.U.clamp((twsKn - P.tws[ti]) / (P.tws[ti + 1] - P.tws[ti]), 0, 1);
    return S.U.lerp(P.beat[ti], P.beat[ti + 1], tf);
  };
})(window.SCS);
