/* tools/polar.js — generate js/polars.js from the real physics.
   Sweeps TWS × TWA × sheet with the tests/harness loader and records the best
   steady speed and the sheet that achieved it. Run AFTER physics changes:
       node tools/polar.js [specId]
   Writes js/polars.js (S.POLARS). */
'use strict';
const fs = require('fs'), path = require('path');
const H = require(path.join(__dirname, '..', 'tests', 'harness'));

const spec = process.argv[2] || 'centaur';
const TWS = [8, 12, 16, 20];
const TWA = []; for (let a = 35; a <= 175; a += 10) TWA.push(a);

const stw = [], sheet = [], beat = [], run = [];
for (const tws of TWS) {
  const ctx = H.boot({ twsKn: tws, twdDeg: 0 });
  const rowS = [], rowSh = [];
  let bestUp = 0, bestUpA = 45, bestDn = 0, bestDnA = 165;
  for (const twa of TWA) {
    const r = H.bestSTW(ctx, spec, twa, { seconds: 45 });
    rowS.push(Math.round(r.stw * 100) / 100);
    rowSh.push(r.sheet);
    const vmg = r.stw * Math.cos((twa * Math.PI) / 180);
    if (vmg > bestUp) { bestUp = vmg; bestUpA = twa; }
    if (-vmg > bestDn) { bestDn = -vmg; bestDnA = twa; }
    process.stderr.write(`tws ${tws} twa ${twa} -> ${r.stw.toFixed(2)}kn @ ${r.sheet}\n`);
  }
  stw.push(rowS); sheet.push(rowSh); beat.push(bestUpA); run.push(bestDnA);
}

const out =
  '/* polars.js — GENERATED by tools/polar.js from the live physics (' + spec + ').\n' +
  '   Best steady STW (kn) and the sheet that achieved it, by TWS x TWA.\n' +
  '   Regenerate after any change to the sail model:  node tools/polar.js */\n' +
  '(function (S) {\n' +
  "  'use strict';\n" +
  '  S.POLARS = {\n' +
  '    spec: ' + JSON.stringify(spec) + ',\n' +
  '    tws: ' + JSON.stringify(TWS) + ',\n' +
  '    twa: ' + JSON.stringify(TWA) + ',\n' +
  '    stw: ' + JSON.stringify(stw) + ',\n' +
  '    sheet: ' + JSON.stringify(sheet) + ',\n' +
  '    beat: ' + JSON.stringify(beat) + ',   // TWA of best upwind VMG per TWS\n' +
  '    run: ' + JSON.stringify(run) + '     // TWA of best downwind VMG per TWS\n' +
  '  };\n' +
  '  /** target boat speed (kn) at this true wind, linearly interpolated */\n' +
  '  S.POLARS.target = function (twsKn, twaDeg) {\n' +
  '    var P = S.POLARS, U = S.U;\n' +
  '    var a = Math.abs(twaDeg);\n' +
  '    if (a < P.twa[0]) a = P.twa[0];\n' +
  '    if (a > P.twa[P.twa.length - 1]) a = P.twa[P.twa.length - 1];\n' +
  '    var ti = 0; while (ti < P.tws.length - 2 && P.tws[ti + 1] < twsKn) ti++;\n' +
  '    var ai = 0; while (ai < P.twa.length - 2 && P.twa[ai + 1] < a) ai++;\n' +
  '    var tf = U.clamp((twsKn - P.tws[ti]) / (P.tws[ti + 1] - P.tws[ti]), 0, 1);\n' +
  '    var af = U.clamp((a - P.twa[ai]) / (P.twa[ai + 1] - P.twa[ai]), 0, 1);\n' +
  '    var lo = U.lerp(P.stw[ti][ai], P.stw[ti][ai + 1], af);\n' +
  '    var hi = U.lerp(P.stw[ti + 1][ai], P.stw[ti + 1][ai + 1], af);\n' +
  '    return U.lerp(lo, hi, tf);\n' +
  '  };\n' +
  '  /** best beat angle (deg TWA) at this wind speed */\n' +
  '  S.POLARS.beatAt = function (twsKn) {\n' +
  '    var P = S.POLARS;\n' +
  '    var ti = 0; while (ti < P.tws.length - 2 && P.tws[ti + 1] < twsKn) ti++;\n' +
  '    var tf = S.U.clamp((twsKn - P.tws[ti]) / (P.tws[ti + 1] - P.tws[ti]), 0, 1);\n' +
  '    return S.U.lerp(P.beat[ti], P.beat[ti + 1], tf);\n' +
  '  };\n' +
  '})(window.SCS);\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'polars.js'), out);
console.log('wrote js/polars.js');
